#!/usr/bin/env bash

# Installs & configures fail2ban for a running nginx instance.

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

[[ $EUID -eq 0 ]] || error "Please run as root: sudo bash $0"

NGINX_ACCESS_LOG="${NGINX_ACCESS_LOG:-/var/log/nginx/access.log}"
NGINX_ERROR_LOG="${NGINX_ERROR_LOG:-/var/log/nginx/error.log}"

if [[ ! -f "$NGINX_ACCESS_LOG" ]]; then
  DETECTED=$(nginx -T 2>/dev/null | grep -E '^\s*access_log\s' | awk '{print $2}' | tr -d ';' | head -1 || true)
  [[ -n "$DETECTED" && "$DETECTED" != "off" ]] && NGINX_ACCESS_LOG="$DETECTED"
fi
if [[ ! -f "$NGINX_ERROR_LOG" ]]; then
  DETECTED=$(nginx -T 2>/dev/null | grep -E '^\s*error_log\s' | awk '{print $2}' | tr -d ';' | head -1 || true)
  [[ -n "$DETECTED" && "$DETECTED" != "off" ]] && NGINX_ERROR_LOG="$DETECTED"
fi

info "Nginx access log : $NGINX_ACCESS_LOG"
info "Nginx error  log : $NGINX_ERROR_LOG"

[[ -f "$NGINX_ACCESS_LOG" ]] || warn "Access log not found yet — fail2ban will watch for it once nginx writes to it."
[[ -f "$NGINX_ERROR_LOG"  ]] || warn "Error log  not found yet — same as above."

if ! command -v fail2ban-server &>/dev/null; then
  info "Installing fail2ban..."
  apt-get update -qq
  apt-get install -y -qq fail2ban
else
  info "fail2ban already installed: $(fail2ban-server --version | head -1)"
fi


JAIL_FILE="/etc/fail2ban/jail.d/nginx.conf"
info "Writing $JAIL_FILE ..."
cat > "$JAIL_FILE" <<EOF
# Auto-generated by setup_fail2ban_nginx.sh — safe to edit.
# This file only adds nginx jails; nothing else is changed.

[DEFAULT]
# Ban duration (seconds). Default 10 min; raise for stricter setups.
bantime  = 600
# Window in which maxretry violations must occur
findtime = 600
# Hits before ban
maxretry = 5
# Use systemd backend if journald is available, else auto
backend  = auto

[nginx-http-auth]
enabled  = true
port     = http,https
logpath  = ${NGINX_ACCESS_LOG}
maxretry = 5

[nginx-botsearch]
enabled  = true
port     = http,https
logpath  = ${NGINX_ACCESS_LOG}
maxretry = 2

[nginx-noscript]
enabled  = true
port     = http,https
logpath  = ${NGINX_ACCESS_LOG}
maxretry = 6

[nginx-badbots]
enabled  = true
port     = http,https
logpath  = ${NGINX_ACCESS_LOG}
maxretry = 2

[nginx-nohome]
enabled  = false   # enable if you use named virtual hosts only
port     = http,https
logpath  = ${NGINX_ACCESS_LOG}
maxretry = 2

[nginx-noagent]
enabled  = false   # enable to drop requests with no User-Agent
port     = http,https
logpath  = ${NGINX_ACCESS_LOG}
maxretry = 2
EOF

info "Jail config written."

#write filter files (Ubuntus fail2ban package omits some)
FILTER_DIR="/etc/fail2ban/filter.d"
info "Writing filter files to $FILTER_DIR ..."

#nginx-http-auth usually present,but write if missing
if [[ ! -f "$FILTER_DIR/nginx-http-auth.conf" ]]; then
  info "  Writing nginx-http-auth.conf"
  cat > "$FILTER_DIR/nginx-http-auth.conf" <<'FILTER'
[Definition]
failregex = ^ \[error\] \d+#\d+: \*\d+ user "(?:[^"]+)" was not found in "[^"]*", client: <HOST>,
            ^ \[error\] \d+#\d+: \*\d+ no user/password was provided for basic authentication, client: <HOST>,
            ^ \[error\] \d+#\d+: \*\d+ user "(?:[^"]+)": password mismatch, client: <HOST>,
ignoreregex =
FILTER
fi

if [[ ! -f "$FILTER_DIR/nginx-botsearch.conf" ]]; then
  info "  Writing nginx-botsearch.conf"
  cat > "$FILTER_DIR/nginx-botsearch.conf" <<'FILTER'
[Definition]
failregex = ^<HOST> .* "(GET|POST|HEAD) .*\.(php|asp|aspx|jsp|cgi|py|pl|sh|bat|exe|dll|ini|env|bak|old|sql|tar|gz|zip|rar|7z|log|conf|config|yml|yaml|json|xml|txt|md|git|svn|htaccess|htpasswd)\b.*" (4\d\d|3\d\d) \d+
ignoreregex =
FILTER
fi

if [[ ! -f "$FILTER_DIR/nginx-noscript.conf" ]]; then
  info "  Writing nginx-noscript.conf"
  cat > "$FILTER_DIR/nginx-noscript.conf" <<'FILTER'
[Definition]
# Block clients repeatedly requesting script extensions that don't exist
failregex = ^<HOST> -.*GET.*(\.php|\.asp|\.exe|\.pl|\.cgi|\.scgi)
ignoreregex =
FILTER
fi

# nginx-badbots — commonly missing on Ubuntu
# All user-agents are inlined directly into the failregex.
if [[ ! -f "$FILTER_DIR/nginx-badbots.conf" ]]; then
  info "  Writing nginx-badbots.conf"
  cat > "$FILTER_DIR/nginx-badbots.conf" <<'FILTER'
[Definition]
# Matches well-known malicious/scraper user-agents (inlined — no interpolation)
failregex = ^<HOST> .* ".*" \d+ \d+ ".*" "(?:Atomic_Email_Hunter|atSpider|autoemailspider|AhrefsBot|MJ12bot|DotBot|SemrushBot|BLEXBot|MegaIndex|spbot|Scrapy|python-requests|zgrab|masscan|sqlmap|nikto|dirbuster|gobuster|nuclei|wfuzz|EmailCollector|WebEMailExtrac|TrackBack|SiteSucker|ChinaClaw|Custo|DISCo|DIIbot|DittoSpyder|Download Demon|Download Devil|Download Wonder|Drip|EBrowse|EmailSiphon|EmailWolf|EroCrawler|Exabot|ExtractorPro|EyeNetIE|FrontPage|Go!Zilla|GoZilla|GrabNet|Grafula|HTTrack|humanlinks|IlseBot|Image Stripper|Image Sucker|InterGET|Internet Ninja|InternetSeer|JennyBot|JetCar|larbin|LeechFTP|LexiBot|libwww|LinkextractorPro|LinkScan|LinkWalker|lwp-trivial|Memo|MIDown tool|Navroad|NearSite|NetAnts|NetMechanic|NetSpider|Net Vampire|NetZip|NimbleCrawler|Ninja|NPBot|Octopus|Offline Explorer|Offline Navigator|Openfind|PageGrabber|pavuk|PeoplePal|Pockey|ProPowerBot|ProWebWalker|psbot|RealDownload|ReGet|Roverbot|ScrubtheSite|SiteSnagger|SlySearch|SmartDownload|Snapbot|Snoopy|sogou spider|SpaceBison|Spinn3r|Szukacz|Teleport|Telesoft|TurnitinBot|Vacuum|VoidEYE|Web Image Collector|Web Sucker|WebAuto|WebBandit|WebCopier|WebFetch|WebLeacher|WebReaper|WebSauger|WebStripper|WebWhacker|WebZIP|Wget|WWWOFFLE|Xaldon WebSpider|Yandex|Zeus)[^"]*"
ignoreregex =
FILTER
fi

# nginx-nohomewrite if missing
if [[ ! -f "$FILTER_DIR/nginx-nohome.conf" ]]; then
  cat > "$FILTER_DIR/nginx-nohome.conf" <<'FILTER'
[Definition]
failregex = ^<HOST> .* "GET http[s]?://\d+\.\d+\.\d+\.\d+
ignoreregex =
FILTER
fi

if [[ ! -f "$FILTER_DIR/nginx-noagent.conf" ]]; then
  cat > "$FILTER_DIR/nginx-noagent.conf" <<'FILTER'
[Definition]
failregex = ^<HOST> .* "-"$
ignoreregex =
FILTER
fi

info "All filter files ready."

#enable &(re)start fail2ban
info "Enabling fail2ban service..."
systemctl enable fail2ban

if systemctl is-active --quiet fail2ban; then
  info "Reloading fail2ban (no nginx restart)..."
  fail2ban-client reload
else
  info "Starting fail2ban..."
  systemctl start fail2ban
fi

echo ""
info "=== Active jails ==="
fail2ban-client status 2>/dev/null || true

echo ""
info "Done. Nginx was not touched."
info "Useful commands:"
echo "  sudo fail2ban-client status nginx-http-auth   # see ban list for a jail"
echo "  sudo fail2ban-client set nginx-http-auth unbanip <IP>   # unban an IP"
echo "  sudo fail2ban-client reload                  # pick up config changes"
echo "  sudo journalctl -u fail2ban -f               # live logs"
